### ISSUE TITLE
Add packages for 2022

### ISSUE THREAD

**Issue by ajwills72** [PlymouthPsychology/installR#4]
Following package(s) need to be added to install script:

| package | version |
| ----------- | ---------- |
| apaTables | >= 2.0.8 |

**Comment by benwhalley** [comment]
ok - have done this on the server (I haven't explicitly added `rpart` to suggested packages because it's already a dependency and think it would have been ok if we hadn't been upgrading).

```
> as.data.frame(installed.packages()) %>% filter(Package=="apaTables")
            Package                       LibPath Version Priority      Depends
apaTables apaTables /usr/local/lib/R/site-library   2.0.8     <NA> R (>= 3.1.2)
                                                                Imports
```
